Multivendor/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('vendor.urls')),
    path('',include('product.urls')),
    path('cart/',include('cart.urls')), 
    path('',include('order.urls')),
    path('',include('notification.urls')),
    path('inbox/notifications/',include('notifications.urls'),name='notifications'),
    

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    
    path('',cart_details,name='cart'),
    path('success/',success,name='success')
]

product/urls.py
import imp


from django.urls import path
from .views import *
urlpatterns = [
    path('create_product',create_product,name='create_product'),
    path('edit_product/<int:product_id>',edit_product,name='edit_product'),
    path('<slug:category_slug>/<slug:subcategory_slug>/<product_slug>',product,name='product'),
    path('<slug:category_slug>',category,name='category'),
    path('<slug:category_slug>/<slug:subcategory_slug>',subcategory,name='subcategory'),
    path('search/',search,name='search')
    
]

product/models.py
from cloudinary.models import CloudinaryField
from django.db import models
from vendor.models import Vendor
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    ordering = models.IntegerField(default=0)
    
    class Meta:
        ordering =['ordering']
    def __str__(self):
        return self.name

class SubCategory(models.Model):
    category = models.ForeignKey(Category,related_name='sub_categories',on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    ordering = models.IntegerField(default=0)
    
    class Meta:
        ordering =['ordering']
    def __str__(self):
        return self.name

class Album(models.Model):
    thumb = CloudinaryField()
    def __str__(self):
        return f"album-{self.product.title}"
class Image(models.Model):
    image = CloudinaryField()
    #album= models.ForeignKey('product.album',related_name='images',on_delete=models.CASCADE)
    product= models.ForeignKey('product.product',related_name='images',on_delete=models.CASCADE)


class Review(models.Model):
    # rate = models.DecimalField(max_digits=1,default=0.5,decimal_places=1)
    rate = models.IntegerField(default=1)
    text = RichTextField()
    user = models.ForeignKey(User,related_name='reviews' , on_delete=models.CASCADE)
    product = models.ForeignKey('product.Product',related_name='reviews',on_delete=models.CASCADE)


class Product(models.Model):
    title = models.CharField(max_length=255)
    price = models.PositiveIntegerField(default=0)
    desc = RichTextField()
    slug = models.SlugField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    thumb = CloudinaryField()
    quantity = models.IntegerField(default=1)
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    Subcategory = models.ForeignKey(SubCategory,related_name='products',on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor,related_name='products',on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    album = models.OneToOneField(Album,related_name='product',on_delete=models.CASCADE,null=True,blank=True)
    favorites = models.ManyToManyField(User,related_name='favorites', blank=True,null=True)
    sizes = models.ManyToManyField("product.Size", related_name='products', null=True,blank=True)
    colors = models.ManyToManyField("product.Color", related_name='products' , null=True,blank=True)
    
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-date']


class Color(models.Model):
    name = models.CharField(max_length=60,unique=True)
    code = models.CharField(max_length=150,unique=True)
    def __str__(self) :
        return self.name

class Size(models.Model):
    name = models.CharField(max_length=60,unique=True)
    #code = models.CharField(max_length=150,unique=True)
    def __str__(self) :
        return self.name

product/forms.py
from email.policy import default
from django import forms
from .models import *
from cloudinary.models import CloudinaryField
class ProductForm(forms.ModelForm):
    #thumb =forms.ImageField(required=False, upload_to='products/thumbs')
    class Meta:
        model = Product
        fields = ['title','thumb','desc','price','category']


class AddToCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1 )

product/views.py
from audioop import reverse
import random

from core.models import Banner
from .models import Image, Review, Size, SubCategory
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.text import slugify

from django.contrib import messages
from cart.cart import Cart
from .forms import AddToCartForm

from product.forms import ProductForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from product.models import Category, Product
from django.db.models import Q
from notifications.signals import notify
 
acer = User.objects.get(username='acer')

def search(req):
        query = req.GET.get('query','')
        category = req.GET.get('category','')
        
        #products = Product.objects.filter(title=query)
        if query :
                products = Product.objects.filter(Q(title__icontains=query) | Q(desc__icontains=query ))
                if category :
                       products =  products.filter(category__slug=category)
        return render(req,'product/search.html',{'products':products,'query':query})

def create_product(req):
    if req.method == 'POST':
        form = ProductForm(req.POST,req.FILES)
        # if form.is_valid():
        #         product = form.save(commit=False)
        #         product.vendor = req.user.vendor
        #         product.slug = slugify(product.title)
        #         product.save()
        title = req.POST['title']
        thumb = req.FILES['thumb']
        desc = req.POST['desc']
        price = req.POST['price']
        quantity = req.POST['quantity']
        images = req.FILES.getlist('images')
        category = Category.objects.get(id=int(req.POST['category']))
        # product = Product.objects.create(title=title,thumb=thumb,desc=desc,price=price,category=category)
        product = Product()
        
        product.title=title
        product.thumb=thumb
        product.desc=desc
        product.price=price
        product.quantity=quantity
        product.category=category
        product.vendor = req.user.vendor
        product.slug = slugify(product.title)
        product.save()
        if images:
                for image in images :
                        Image.objects.create(product=product,image=image)
        
        return redirect('vendor_products') 
    else:
            form = ProductForm()

    return render(req,'product/create_product.html',{"form":form})

def edit_product(req,product_id):
    product = Product.objects.get(id=product_id)
    if req.method == 'POST':
        
        form = ProductForm(req.POST,req.FILES)
        # if form.is_valid():
        #         product = form.save(commit=False)
        #         product.vendor = req.user.vendor
        #         product.slug = slugify(product.title)
        #         product.save()
        title = req.POST['title']
        thumb = req.FILES['thumb']
        desc = req.POST['desc']
        price = req.POST['price']
        images = req.FILES.getlist('images')
        category = Category.objects.get(id=int(req.POST['category']))
        subcategory = SubCategory.objects.get(id=int(req.POST['sub_category']))
        sizes =  req.POST.getlist('sizes')
        colors =  req.POST.getlist('colors')

        # product = Product.objects.create(title=title,thumb=thumb,desc=desc,price=price,category=category)
        
        
        product.title=title
        product.thumb=thumb
        product.desc=desc
        product.price=price
        product.category=category
        product.vendor = req.user.vendor
        product.slug = slugify(product.title,allow_unicode=True)
        product.Subcatgory = subcategory
        product.save()
        notify.send(acer,recipient=req.user,verb='Your Product has been Updated successfuly !! ',level='success')
        if sizes:
                if product.sizes.all():
                        product.sizes.clear()
                for size in sizes:
                        product.sizes.add(size)
        if colors:
                if product.colors.all():
                        product.colors.clear()
                for color in colors:
                        product.colors.add(color)
        if images:
                if product.images:
                        for image in product.images.all() :
                                image.delete()
                for image in images :
                        Image.objects.create(product=product,image=image)
                        
        
        return redirect('vendor_products') 
    else:
            form = ProductForm()

    return render(req,'product/edit_product.html',{"form":form,'product':product})     
def product(req,category_slug,subcategory_slug,product_slug):
        cart = Cart(req)
        product = get_object_or_404(Product,category__slug=category_slug,Subcategory__slug=subcategory_slug,slug=product_slug)
        if product.status :
                
                review_text = req.GET.get('desc','')
                review_rate = req.GET.get('rate','')
                review = None
                try:
                         review=Review.objects.get(user=req.user,product=product)
                except Exception:
                        print('something is wrong')
                if review_rate and review_text :
                        if review:
                                review.rate = review_rate
                                review.text = review_text
                                review.save()
                        else:
                              Review.objects.create(user=req.user,product=product,rate=review_rate,text=review_text)  

                        return redirect('product' , category_slug= product.category.slug ,subcategory_slug= product.Subcategory.slug , product_slug= product.slug)
                if req.method == 'POST':
                        quantity = req.POST['quantity']
                        color = req.POST.get('color',False)
                        size = req.POST.get('size',False) 
                        cart.add(product_id=product.id ,quantity=quantity,update_quantity=False)
                        if color:
                                        cart.addColor(product_id=product.id,color=color)
                        if size :
                                cart.addSize(product_id=product.id,size=size)
                        if str(product.id) in cart.cart.keys() :
                                messages.success(req,'The Product was added successfully to the cart !')
                                return redirect('product' , category_slug= product.category.slug ,subcategory_slug= product.Subcategory.slug , product_slug= product.slug)
                        
                else:
                        form = AddToCartForm()
        else:
                if req.user == product.vendor.created_by  :
                        messages.warning(req ,'This Product hasn"t been active yet , please wait tl it be activated ')
                        return redirect('vendor_products')
                else:
                        return redirect('frontpage')

        semillar_products = list(product.category.products.exclude(id=product.id))
        #semillar_products = Product.objects.filter(category__slug=category_slug).exclude(id=product.id)
        if len(semillar_products) >=4:
                 semillar_products= random.sample(semillar_products,4)
        
        return render(req,'product/product.html',{'product':product,'semillar_products':semillar_products,'reviews':Review.objects.filter(product=product),'rev':review})

def category(req,category_slug):
    category = get_object_or_404(Category,slug=category_slug)
    products = Product.objects.filter(category__slug =category_slug,)
    product_id = req.GET.get('product_id','')
    favorites_id = req.GET.get('favorites_id','')
    favorites_remove_id =req.GET.get('favorites_remove_id','')
    cart =Cart(req)
    update_id = req.GET.get('change_quantity','')
    quantity = req.GET.get('quantity','')
    remove_id = req.GET.get('remove_from_cart','')

    if update_id != '':
        Cart(req).add(product_id=update_id,quantity=quantity,update_quantity=True)
    if remove_id != '':
        Cart(req).remove(remove_id)
    if product_id:
        cart.add(product_id=product_id)
        messages.success(req,'The Product was added successfully to the cart !')
    if favorites_id :
        product = Product.objects.get(id=favorites_id)
        product.favorites.add(req.user)
    if favorites_remove_id:
        product = Product.objects.get(id=favorites_remove_id)
        product.favorites.remove(req.user)
    return render(req,'product/category.html',{'category':category,'products':products})

def subcategory(req,category_slug,subcategory_slug):
    category = get_object_or_404(Category,slug=category_slug)
    subcategory = get_object_or_404(SubCategory,slug=subcategory_slug,category__slug=category_slug)
    products = Product.objects.filter(category=category,Subcategory=subcategory)
    product_id = req.GET.get('product_id','')
    favorites_id = req.GET.get('favorites_id','')
    favorites_remove_id =req.GET.get('favorites_remove_id','')
    cart =Cart(req)
    update_id = req.GET.get('change_quantity','')
    quantity = req.GET.get('quantity','')
    remove_id = req.GET.get('remove_from_cart','')

    if update_id != '':
        Cart(req).add(product_id=update_id,quantity=quantity,update_quantity=True)
    if remove_id != '':
        Cart(req).remove(remove_id)
    if product_id:
        cart.add(product_id=product_id)
        messages.success(req,'The Product was added successfully to the cart !')
    if favorites_id :
        product = Product.objects.get(id=favorites_id)
        product.favorites.add(req.user)
    if favorites_remove_id:
        product = Product.objects.get(id=favorites_remove_id)
        product.favorites.remove(req.user)

product/templates/product/category.html
{% extends 'core/base.html' %}

{% block title %} {{category.name}} | products {% endblock title %}

{% block content %}
    <div class="w-full  bg-gray-00">
        <div class="flex justify-center mt-20">
            <h1 class="text-3xl">
                {{ category.name }} {% if subcategory  %} / {{ subcategory.name }} {% endif %}
            </h1>
        </div>
                    <hr class="mt-10 ">

            <div class="w-full flex justiif-center mt-20">
                <div class="w-4/5 min-h-40 flex flex-warp  ">
                        {% if products %}
                            {% for  product in products %}
                                {% include 'product/products_list.html' %}
                            {% endfor %}
                        {% endif %}
                </div>
            </div>

    </div>
{% endblock content %}

product/templates/product/create_product.html
{% extends 'core/base.html' %}
{% block title %}
Creat Product
{% endblock title %}

{% block content %}
<div class="full flex justify-center">
  <form method="post"  class=" space-y-5 w-2/3 " action="" enctype='multipart/form-data' >
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
        
        <div class="field">
            <label class="label">Title</label>
            <div class="control">
              <input class="input" type="text" name="title" maxlength="255" required="" id="id_title">
            </div>
            <p class="help">This is a help text</p>
          </div>
        
        
      
    
      
      <div class="flex space-x-4">
        <div class="field">
          <label class="label">Thumbnail</label>
          <div class="file has-name">
              <label class="file-label">
                <input class="file-input" type="file" name="thumb" required="" id="id_thumb">
                <span class="file-cta">
                  <span class="file-icon">
                    <i class="fas fa-upload"></i>
                  </span>
                  <span class="file-label">
                    Choose a file…
                  </span>
                </span>
                <span class="file-name">
                  
                </span>
              </label>
            </div>
          
          
        </div >

        <p>
          <div class="field">
              <label class="label">Price</label>
              <div class="control">
                <input class="input" type="text" type="number" name="price" value="0" min="0" required="" id="id_price">
              </div>
              <p class="help">This is a help text</p>
            </div>
          
      
        </p>
        <div class="field">
          <label class="label">Quantity</label>
          <div class="control">
            <input class="input w-14 " type="text" type="number" name="quantity" value="1" min="0" required="" id="id_quantity">
          </div>
          <p class="help">This is a help text</p>
        </div>
      
      
        
        <p>
  
          <div class="field">
              <label for="" class="label">Category</label>
              <div class="select is-info">
                  <select name="category" >
                    <option value="" selected="">Select dropdown</option>
                    {% for category in menu_categories %}
                    <option value="{{ category.id }}" >{{  category.name }}</option>
                    {% endfor %}
                  </select>
                </div>
          </div>
        </p> 
      </div>
     <div class="field w-full">
      <label for="" class="label font-light">Extra images</label>
      <div class="file has-name is-boxed w-full ">
        
        <label class="file-label w-full">
          <input class="file-input" type="file" name="images" multiple>
          <span class="file-cta w-full">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Choose a file…
            </span>
          </span>
          
        </label>
      </div>
     </div>
      <div class=" field ">
        <label class="label">Desc</label>
        <textarea class="textarea" placeholder="Desc" cols="40" id="id_desc" name="desc" rows="10" required="" data-processed="0" data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 835, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;language&quot;: &quot;en-us&quot;}" data-external-plugin-resources="[]" data-id="id_desc" data-type="ckeditortype"></textarea>
      </div>

    
      
      
    
        

    <button class="p-4 bg-sky-600 text-gray-50 font-semibold m-5 " > Create Product </button>
</form>
</div>
{% endblock content %}

{% block scripts %}

<script>
  
  const fileInput = document.querySelector('#file-js-example input[type=file]');
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('#file-js-example .file-name');
      fileName.textContent = fileInput.files[0].name;
    }

  }

  CKEDITOR.replace( 'desc' );
</script>
{% endblock  %}

product/templates/product/edit_product.html
{% extends 'core/base.html' %}
{% block title %}
edit Product
{% endblock title %}

{% block content %}
<div class="full flex justify-center">
  <form method="post"  class=" space-y-5 w-2/3 " action="" enctype='multipart/form-data' >
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
        
        <div class="field">
            <label class="label">Title</label>
            <div class="control">
              <input class="input" type="text" name="title" maxlength="255" required="" value={{product.title}} id="id_title">
            </div>
            <p class="help">This is a help text</p>
          </div>
        
        
      
    
      
      <div class="flex space-x-4">
        <div class="field">
          <label class="label">Thumbnail</label>
          <div class="file has-name">
              <label class="file-label">
                <input class="file-input" type="file"  name="thumb" required="" id="id_thumb">
                <span class="file-cta">
                  <span class="file-icon">
                    <i class="fas fa-upload"></i>
                  </span>
                  <span class="file-label">
                    Choose a file…
                  </span>
                </span>
                <span class="file-name">
                  
                </span>
              </label>
            </div>
          
          
        </div >

        <p>
          <div class="field">
              <label class="label">Price</label>
              <div class="control">
                <input class="input" value={{product.price}} type="text" type="number" name="price"  min="0" required="" id="id_price">
              </div>
              <p class="help">This is a help text</p>
            </div>
          
      
        </p>
      
        
        <p>
  
          <div class="field">
              <label for="" class="label">Category</label>
              <div class="select is-info">
                  <select name="category" >
                    <option value="" >Select dropdown</option>
                    {% for category in menu_categories %}
                    <option value="{{ category.id }}"  {% if category.id == product.category.id  %} selected {% endif %} >{{  category.name }}</option>
                    {% endfor %}
                    
                  </select>
                </div>
          </div>
        </p> 
      </div>
     <div class="field w-full">
      <label for="" class="label font-light">Extra images</label>
      <div class="file has-name is-boxed w-full ">
        
        <label class="file-label w-full">
          <input class="file-input" type="file" name="images" value={{product.images.all}} multiple>
          <span class="file-cta w-full">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Choose a file…
            </span>
          </span>
          
        </label>
      </div>
     </div>
      <div class=" field ">
        <label class="label">Desc</label>
        <textarea class="textarea" value={{ product.desc }} placeholder="Desc" cols="40" id="id_desc" name="desc" rows="10" required="" data-processed="0" data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 835, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;language&quot;: &quot;en-us&quot;}" data-external-plugin-resources="[]" data-id="id_desc" data-type="ckeditortype"></textarea>
      </div>

    
      
      
    
        

    <button class="p-4 bg-sky-600 text-gray-50 font-semibold m-5 " > Edit Product </button>
</form>
</div>
{% endblock content %}

{% block scripts %}
<script>
  const fileInput = document.querySelector('#file-js-example input[type=file]');
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('#file-js-example .file-name');
      fileName.textContent = fileInput.files[0].name;
    }
  }
</script>
{% endblock  %}

product/templates/product/products_list.html
{% load filters %}
{% load tags %}

<div id='product' class="  md:w-64 h-56 w-52 sm:w-48 bg-gray-100   mx-0 rounded-md relative px-2 relative ">
        {% if user in product.favorites.all %}
            <a id='favorite_btn' href='?favorites_remove_id={{ product.id }}'>
                <i class="ri-heart-2-fill absolute right-4 top-3 text-red-400 ri-2x"></i>
            </a>
        {% else %}
        <a id='favorite_btn' href='?favorites_id={{ product.id }}'>
            <i class="ri-heart-2-line absolute right-4 top-3 text-gray-400 ri-2x"></i>
        </a>
        {% endif %}
        <a  class='absolute right-4 bottom-3 z-10' href='?product_id={{product.id}}'>
            <i id='add_to_cart_btn' class="ri-add-circle-line ri-2x text-sky-600 "></i>
        </a>
        <div class='w-full h-20 flex justify-center mt-10 '>
            <img class=' w-4/5  ' src={{ product.thumb.url}} alt="not found">
        </div>
         <div class="w-full p-2 absolute bottom-0 ">
            <a href="{% url 'product' product.category.slug product.Subcategory.slug product.slug %}" ><h1 id='title' class="  text-lg font-semibold my-2">{{ product.title | truncatechars:10 }}</h1></a>
            <div class='w-full flex justify-between mt-2 items-center '>
            <p class=" text-gray-800 text-md font-bold" id='price'>${{ product.price }}</p>
            
            </div>
        </div>
</div>

product/templates/product/search-form.html
<form action="{% url 'search' %}"  method="get">
    <div class="w-full h-14 flex items-center justify-between     ">
        <div id="categories-btn" class=" hidden  group w-32 relative cursor-pointer  rounded-md h-32  border-0 border-sky-600 mx-10 flex justify-center items-center  ">
            <div class="w-full p-2  space-x-2  lg:flex ">
                <span class="text-sky-600">Category</span>
            </div>
            <div id="categories-menu" class="fixed top-0 left-32 w-80 z-20 min-w-80 group-hover:visible invisible    translate-y-28 group-hover:translate-y-20 transform duration-200 ">
                {% include 'core/components/categories_menu.html' %}
            </div>
        </div>
       <div class="w-full flex space-x-0">
        <select class="w-5/12   relative z-10 h-10 bg-sky-00 border-2 border-r-0 border-sky-600  px-2 outline-none   text-sky-600 rounded-l-full  flex justify-center items-center " name="category">
            <option selected value="">Category</option>
            {% for category in menu_categories %}
                <option  value="{{ category.slug }}">{{ category.name }}</option>
            {% endfor %}
        </select>
    <div class="w-10/12 flex -space-x-4 ">
        <input class="w-full  h-10 pl-4 py-1 relative z-[20]  border-2 border-l-0 rounded-l-none    outline-none border-r-8 rounded-r-full border-sky-600  " placeholder="Search for anything  " type="search" name="query" id="">
    <button class="lg:w-2/12 w-24 h-10 bg-sky-600 relative z-[10] text-white rounded-r-full  flex justify-center items-center " >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M18.031 16.617l4.283 4.282-1.415 1.415-4.282-4.283A8.96 8.96 0 0 1 11 20c-4.968 0-9-4.032-9-9s4.032-9 9-9 9 4.032 9 9a8.96 8.96 0 0 1-1.969 5.617zm-2.006-.742A6.977 6.977 0 0 0 18 11c0-3.868-3.133-7-7-7-3.868 0-7 3.132-7 7 0 3.867 3.132 7 7 7a6.977 6.977 0 0 0 4.875-1.975l.15-.15z" fill="rgba(255,255,255,1)"/></svg>
    </button>
    </div>
       </div>
    </div>
</form>

product/templates/product/search.html
{% extends 'core/base.html' %}

{% block title %}  searching.. for {{query}} {% endblock title %}

{% block content %}
    <div class="w-full  bg-gray-00 my-10 flex space-x-10 p-4 justify-center">
            
            
            <div class="w-[80%] flex justiif-center ">
                <div class="w-full min-h-40  grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4  mt-10 ">
                        
                            {% for  product in products %}
                                {% include 'product/products_list.html' %}
                            {% endfor %}
                        
                </div>
            </div>

    </div>
{% endblock content %}